

export const postsTypes = {
    GET_POSTS: 'GET POSTS',
    GET_CURRENT_POST: 'GET_CURRENT_POST',
    CLEAR_POST: 'CLEAR_POST',
    IS_FETCHING: 'IS_FETCHING',
}

export const asyncPostsTypes = {
    ASYNC_GET_POSTS:'ASYNC GET POSTS',
    ASYNC_GET_COMMENTS: 'ASYNC GET COMMENTS',
}